name: flutter_arcore_plugin
description: "Clone of arcore_flutter_plugin, clone in order to fix Kotlin gradle plugin version"
version: 0.1.0
homePage: https://github.com

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4
  equatable: ^2.0.5
  meta: ^1.10.0

flutter:
  plugin:
    platforms:
      android:
        package: com.mfl.flutter_arcore_plugin
        pluginClass: ArcoreFlutterPlugin
